# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgfKkkGMJJsjL3InvwEBgoLZ5okmwx8T
"""

# Daily Task Organizer

# Step 1: Create checklist for the day
def get_checklist():
    print("Enter your tasks for today. Type 'done' when finished:")
    checklist = []
    while True:
        task = input("Task: ").strip()
        if task.lower() == 'done':
            break
        if task:
            checklist.append(task)
    return checklist

# Step 2: Review completed tasks
def get_completed_tasks(checklist):
    print("\nNow mark tasks as completed.")
    completed = []
    for task in checklist:
        response = input(f"Did you complete: '{task}'? (yes/no): ").lower()
        if response in ['yes', 'y']:
            completed.append(task)
    return completed

# Step 3: Determine incomplete tasks
def get_incomplete_tasks(checklist, completed):
    return [task for task in checklist if task not in completed]

# Step 4: Display summary
def show_summary(completed, incomplete):
    print("\n🟢 Completed Tasks:")
    for task in completed:
        print(f"✅ {task}")

    print("\n🔴 Incomplete Tasks:")
    for task in incomplete:
        print(f"❌ {task}")

# Main function to run the program
def main():
    print("📝 Welcome to Your Daily Task Organizer 📝")
    checklist = get_checklist()
    completed = get_completed_tasks(checklist)
    incomplete = get_incomplete_tasks(checklist, completed)
    show_summary(completed, incomplete)

# Run the program
if __name__ == "__main__":
    main()